### ISSUE TITLE
sync upload error by ankidroid

### ISSUE THREAD

**Issue by hqzxjczx** [tsudoko/anki-sync-server#32]
when I upload data by ankidroid, then windows server throw the bellow error: 
```
Traceback (most recent call last):
  File "C:\Python37\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Python37\lib\site-packages\webob\dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "C:\Python37\lib\site-packages\webob\dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "C:\Users\hqzxj\Documents\work\anki-sync-server\ankisyncd\sync_app.py", line 572, in __call__
    result = thread.execute(self.operation_upload, [data['data'], session])
  File "C:\Users\hqzxj\Documents\work\anki-sync-server\ankisyncd\thread.py", line 79, in execute
    raise ret
  File "C:\Users\hqzxj\Documents\work\anki-sync-server\ankisyncd\thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "C:\Users\hqzxj\Documents\work\anki-sync-server\ankisyncd\collection.py", line 44, in execute
    ret = func(*args, **kw)
  File "C:\Users\hqzxj\Documents\work\anki-sync-server\ankisyncd\sync_app.py", line 488, in operation_upload
    return self.full_sync_manager.upload(col, data, session)
  File "C:\Users\hqzxj\Documents\work\anki-sync-server\ankisyncd\full_sync.py", line 28, in upload
    os.rename(temp_db_path, session.get_collection_path())
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\hqzxj\\Documents\\work\\anki-sync-server\\srv\\anki\\ankisyncd\\hqzxjczx\\collection.anki2.tmp' -> 'C:\\Users\\hqzxj\\Documents\\work\\anki-sync-server\\srv\\anki\\ankisyncd\\hqzxjczx\\collection.anki2'
```
ankidroid version is 2.8.4
anki-sync-server is the master version 
windows anki is 2.1.11 
@tsudoko

**Comment by hqzxjczx** [comment]
the problem is resolved. just modify the 'os.rename' to 'os.replace' in the below code: 
``` 
os.rename(temp_db_path, session.get_collection_path())
···
the correct code is 
```
os.replace(temp_db_path, session.get_collection_path())
```
@tsudoko

**Comment by tsudoko** [comment]
Thanks for figuring this out.
