### ISSUE TITLE
Anki Windows 2.1.18 Failed to sync. I'm suggesting a patch

### ISSUE THREAD

**Issue by gzz2000** [tsudoko/anki-sync-server#47]
Version 2.1.18 (fb9d59fe)
Python 3.8.0 Qt 5.14.0 PyQt 5.13.2

![Snipaste_2020-01-16_21-15-35](https://user-images.githubusercontent.com/19143357/72528221-8330e380-38a5-11ea-8cb4-972457451e2a.png)

I got this error and cannot sync the changes made on my android device to my windows computer. After struggling for a while I realized that the server responded a 500. By examining the output (btw I use the docker version and a `docker attach`):

```
ERROR:root:CollectionThread[/app/data/collections/gzz/collection.anki2]: Unable to start(*[], **{}): start() got an unexpected keyword argument 'offset'
Traceback (most recent call last):
  File "/app/anki-sync-server/ankisyncd/thread.py", line 71, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/app/anki-sync-server/ankisyncd/collection.py", line 39, in execute
    ret = func(*args, **kw)
  File "/app/anki-sync-server/ankisyncd/sync_app.py", line 673, in run_func
    res = handler_method(**keyword_args)
TypeError: start() got an unexpected keyword argument 'offset'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/app/anki-sync-server/ankisyncd/sync_app.py", line 605, in __call__
    result = self._execute_handler_method_in_thread(url, data, session)
  File "/app/anki-sync-server/ankisyncd/sync_app.py", line 682, in _execute_handler_method_in_thread
    result = thread.execute(run_func)
  File "/app/anki-sync-server/ankisyncd/thread.py", line 52, in execute
    raise ret
  File "/app/anki-sync-server/ankisyncd/thread.py", line 71, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/app/anki-sync-server/ankisyncd/collection.py", line 39, in execute
    ret = func(*args, **kw)
  File "/app/anki-sync-server/ankisyncd/sync_app.py", line 673, in run_func
    res = handler_method(**keyword_args)
TypeError: start() got an unexpected keyword argument 'offset'
```

It seems that it is a new `offset` argument passed to `SyncCollectionHandler.start` causes the trouble. I found that it's always a `None` in my case so I just added it and ignored it, it just works.
```
    def start(self, minUsn, lnewer, graves={"cards": [], "notes": [], "decks": []}, offset=None):
```

Please check if you also have this problem with Anki 2.1.18. If it's the right thing to do I can make a pull request on this one-line patch.

**Comment by gzz2000** [comment]
There is no problem during the first sync, but the problem arises when trying to sync changes from other client.

**Comment by tsudoko** [comment]
I'm aware of the problem but I'm not sure if just adding `offset` is enough. I wanted to test this a bit more before pushing any changes to make sure there aren't any scheduling discrepancies, but I guess it's better to make it work at all in this case. Feel free to submit a PR if you want.

**Comment by tsudoko** [comment]
> but the `offset` isn't providing any information since I haven't seen anything other than `None` passed over it.

[The offset seems to be used only with the v2 scheduler](https://github.com/ankitects/anki/commit/683edeeb07fbaecdd844597e93bca5deb2e9c51e#diff-e501c88bf7d06d2c8955fe026c9b80b1R135-R140), so your PR would work fine with v1 collections.
