### ISSUE TITLE
Reverse proxy: Server not found on desktop

### ISSUE THREAD

**Issue by ghost** [tsudoko/anki-sync-server#68]
I installed anki-sync-server on my personal server, and I set up a reverse proxy with Nginx so that the sync server is served on https://anki.thaega.fr, 443 port. As far as I can tell, it's running correctly server-side.
However, when I try to sync it with Anki Desktop (version 2.1.26), I get the error 
```Syncing failed:
Server not found. Either your connection is down, or antivirus/firewall software is blocking Anki from connecting to the internet.
```
and nothing shows up on the logs server-side.
The content of `addons21/ankisyncd/__init__.py` are 
```
import anki.sync, anki.hooks, aqt

addr = "https://anki.thaega.fr" # put your server address here
anki.sync.SYNC_BASE = "%s" + addr
def resetHostNum():
    aqt.mw.pm.profile['hostNum'] = None
anki.hooks.addHook("profileLoaded", resetHostNum)
```
I previously had made the mistake of leaving a trailing slash at the end of the address, which gave me the following error
```Syncing failed:
Traceback (most recent call last):
  File "aqt/sync.py", line 397, in run
  File "aqt/sync.py", line 420, in _sync
  File "anki/sync.py", line 571, in hostKey
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
and left some trace in the logs server-side.

I can't log in either using AnkiDroid (without any error messages), however these login attemps do show up on the server logs.

**Comment by AntonOfTheWoods** [comment]
Is there some reason you are not using the supplied addon? https://github.com/tsudoko/anki-sync-server/tree/master/addon. It works great for me, though you may have to use a previous version as 2.1.26 needs some extra configuration to get working. I believe 2.1.19 is working with the current state of this repo.

**Comment by ghost** [comment]
I followed the instructions provided in the Readme, that made no mention of it. I'm going to try it.
I downgraded Anki to 2.1.15 (because I couldn't find a build for 2.1.19), put the addon files in `addons21/ankisyncd`.
I now get the response "AnkiWeb ID or password was incorrect", which is an improvement compared to what I was getting before. I see no trace of this request in the logs, which leads me to suppose that Anki somehow didn't get the message that it should use my custom server.
Should I have filled `config.json` in some way?

**Comment by AntonOfTheWoods** [comment]
Our friend over at https://github.com/kuklinistvan/docker-anki-sync-server has linked to 2.1.19 for various platforms (and provided alternative links if the Anki guys remove the files). Check the Readme there for the links.

The `config.json` gets filled in when you update the `Tools->Preferences->Network` page and activate "Use custom server". If memory serves you may have to close and reopen Anki after filling in this for the first time.

Yes, the `Readme` makes no mention of it, that could be improved.
