### ISSUE TITLE
Collection too large to upload to ankiweb

### ISSUE THREAD

**Issue by epistularum** [tsudoko/anki-sync-server#69]
I have a very large collection (1,636,286 cards) and I get this error when I try to sync from the desktop app.
A smaller collection does work with the same setup.
```
Syncing failed:
Traceback (most recent call last):
  File "aqt\sync.py", line 342, in run
  File "aqt\sync.py", line 396, in _sync
  File "aqt\sync.py", line 428, in _fullSync
  File "anki\sync.py", line 691, in upload
  File "anki\sync.py", line 572, in req
  File "anki\sync.py", line 567, in _buildPostData
Exception: Collection too large to upload to AnkiWeb.
```
edit: I tried manually overwriting "collection.anki2" on the server and it works after that.

**Comment by dobefore** [comment]
Can it sync successfully using a new user account?

**Comment by epistularum** [comment]
Yes, having a smaller/new account does work.
