### ISSUE TITLE
desktop app 2.1.26  username or passwd wrong ,retry

### ISSUE THREAD

**Issue by bartowski-l** [tsudoko/anki-sync-server#75]
always show this error message  who can i help me how fix it i try #63 add some code but it's not work. i can't see the mean of PR? someone can fix this problem? thanks

**Comment by bartowski-l** [comment]
when i close it,another window appears,it says,username or passwd wrong ,retry

**Comment by bartowski-l** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anki/anki-sync-server/ankisyncd/__main__.py", line 8, in <module>
    import ankisyncd.sync_app
  File "/anki/anki-sync-server/ankisyncd/sync_app.py", line 504
    if hkey == None:
                   ^

**Comment by bartowski-l** [comment]
i fix it thank you for everyone

**Comment by bartowski-l** [comment]
i fix it thank you for everyone
