### ISSUE TITLE
One client ot an error while uploading

### ISSUE THREAD

**Issue by HaujetZhao** [tsudoko/anki-sync-server#79]
Here is the log: 

```
[2020-10-11 07:38:58,821]:INFO:ankisyncd:ankisyncd 2.1.0-9-g41205c0 (https://github.com/tsudoko/anki-sync-server)
[2020-10-11 07:38:58,829]:INFO:ankisyncd:Loaded config from /root/anki-sync-server/ankisyncd.conf
[2020-10-11 07:38:58,830]:INFO:ankisyncd.users:Found auth_db_path in config, using SqliteUserManager for auth
[2020-10-11 07:38:58,830]:INFO:ankisyncd.sessions:Found session_db_path in config, using SqliteSessionManager for auth
[2020-10-11 07:38:58,862]:INFO:ankisyncd:Serving HTTP on 0.0.0.0 port 27701...
[2020-10-11 07:39:23,714]:INFO:ankisyncd.CollectionThread[kkk]:Starting...
[2020-10-11 07:39:23,714]:INFO:ankisyncd.CollectionThread[kkk]:Running meta(*[], **{'v': 9, 'cv': 'ankidesktop,2.1.21 (f1734a47),win:10'})
[2020-10-11 07:39:23,724]:INFO:ankisyncd.http:127.0.0.1 "POST /sync/meta HTTP/1.0" 200 114
[2020-10-11 07:39:23,758]:INFO:ankisyncd.CollectionThread[kkk]:Running begin(*[], **{'skey': 'f2ae26dd'})
[2020-10-11 07:39:23,758]:INFO:ankisyncd.http:127.0.0.1 "POST /msync/begin HTTP/1.0" 200 52
[2020-10-11 07:39:23,797]:INFO:ankisyncd.CollectionThread[kkk]:Running mediaChanges(*[], **{'lastUsn': 4149})
[2020-10-11 07:39:23,797]:INFO:ankisyncd.http:127.0.0.1 "POST /msync/mediaChanges HTTP/1.0" 200 23
[2020-10-11 07:39:23,828]:INFO:ankisyncd.CollectionThread[kkk]:Running uploadChanges(*[], **{'data': b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xeb<KQ\xf15\x91\x872\x00\x00\x000\x00\x00\x00\x05\x00\x00\x00_meta\x8b\x8eV*\xb5540\xb746167\xb0\xd016377161\xb10TK\xcb\xb552SK/\xb05\xd0\xcb*HW\xd2QP...'})
[2020-10-11 07:39:23,829]:ERROR:ankisyncd.CollectionThread[kkk]:Unable to uploadChanges(*[], **{'data': b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xeb<KQ\xf15\x91\x872\x00\x00\x000\x00\x00\x00\x05\x00\x00\x00_meta\x8b\x8eV*\xb5540\xb746167\xb0\xd016377161\xb10TK\xcb\xb552SK/\xb05\xd0\xcb*HW\xd2QPR\x8a\x8d\x05\x00PK\x01\x02\x14\x00\x14\x00\x00\x00\x08\x00\xeb<KQ\xf15\x91\x872\x00\x00\x000\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x01\x00\x00\x00\x00_metaPK\x05\x06\x00\x00\x00\x00\x01\x00\x01\x003\x00\x00\x00U\x00\x00\x00\x00\x00'}): 
Traceback (most recent call last):
  File "/root/anki-sync-server/ankisyncd/thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/root/anki-sync-server/ankisyncd/collection.py", line 46, in execute
    ret = func(*args, **kw)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 624, in run_func
    res = handler_method(**keyword_args)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 199, in uploadChanges
    processed_count = self._adopt_media_changes_from_zip(z)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 270, in _adopt_media_changes_from_zip
    assert self.col.media.lastUsn() == oldUsn + processed_count  # TODO: move to some unit test
AssertionError
Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 601, in __call__
    result = self._execute_handler_method_in_thread(url, data, session)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 633, in _execute_handler_method_in_thread
    result = thread.execute(run_func, kw=keyword_args)
  File "/root/anki-sync-server/ankisyncd/thread.py", line 79, in execute
    raise ret
  File "/root/anki-sync-server/ankisyncd/thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/root/anki-sync-server/ankisyncd/collection.py", line 46, in execute
    ret = func(*args, **kw)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 624, in run_func
    res = handler_method(**keyword_args)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 199, in uploadChanges
    processed_count = self._adopt_media_changes_from_zip(z)
  File "/root/anki-sync-server/ankisyncd/sync_app.py", line 270, in _adopt_media_changes_from_zip
    assert self.col.media.lastUsn() == oldUsn + processed_count  # TODO: move to some unit test
AssertionError
```

**Comment by dobefore** [comment]
It occurs sometimes,Maybe VPN ?

**Comment by sunnysab** [comment]
你解决了吗？我这一直是这个问题，Windows版 2.1.39 同步时出错。
手机同步就没这个问题。

Did you solve it? I have always had this problem, and an error occurred during the synchronization of the version 2.1.39 on Windows.
This problem doesn't occur when I use AnkiDroid.
